# Generated by Django 5.1.1 on 2024-10-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_user_is_active_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryManagement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_name', models.CharField(max_length=255)),
                ('inventory_product', models.CharField(max_length=255)),
                ('invetory_platform', models.CharField(max_length=255)),
                ('invetory_prize', models.BigIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'inventory_management',
                'managed': False,
            },
        ),
    ]
