# Generated by Django 5.1.1 on 2024-10-07 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryupdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryUpdate',
            new_name='Inventory',
        ),
    ]
