# Generated by Django 5.1.1 on 2024-10-07 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_inventoryupdate_inventory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='InventoryUpdate',
        ),
        migrations.AlterModelTable(
            name='inventoryupdate',
            table='inventory_management',
        ),
    ]
