# Generated by Django 5.1.1 on 2024-10-07 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_inventory_inventoryupdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryupdate',
            old_name='name',
            new_name='inventory_name',
        ),
        migrations.RenameField(
            model_name='inventoryupdate',
            old_name='product',
            new_name='inventory_product',
        ),
    ]
